title: x-stats
description: "An attempt to becoming an x-pert in football data analytics"
author: Ushnik Mukherjee
email: mukherjee.ushnik@gmail.com
url: "https://u3mukher.github.io/x-stats/"
theme: minima
minima:
  skin: solarized
  social_links:
    github: u3mukher

timezone: America/Toronto
lang: en

markdown: kramdown
highlighter: rouge

# Enable math rendering via kramdown + MathJax
kramdown:
  input: GFM              # GitHub Flavored Markdown
  math_engine: mathjax    # Use MathJax for rendering math
  math_engine_opts:
    # autoprefix adds backslashes if needed for certain LaTeX macros
    # you can include other options if desired
    autoprefix: true


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/

github:
  is_project_page: true

